Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -34,14 +34,8 @@ jobs:
          cd new
          sed -i '/repositories {/i sourceSets {\n  main {\n    java {\n      srcDirs = ["/home/runner/work/mars-rover-kata-java/mars-rover-kata-java/master/src/main/java"]\n    }\n    resources {\n      srcDirs = ["/home/runner/work/mars-rover-kata-java/mars-rover-kata-java/master/resources/"]\n    }\n  }\n}' build.gradle
          cd ..
-
-      - name: Check gradle file
-        run: cd new; cat build.gradle
-        
-      - name: Check source Code
-        run: cd master/src/main/java/com/technologyconversations/kata/marsrover; cat Rover.java
         
       - name: Run new branch tests on master
-        run: cd new; gradle test --rerun-tasks --no-build-cache
+        run: cd new; gradle test --rerun-tasks --no-build-cache; echo "::error::New Tests fail on Master Branch" && exit 24
 
       
